---
type: yml

application:
  graceful_shutdown_timeout_in_seconds: 10
  profiling_port: 1002
  enable_profiling: true

http_server:
  port: 8002

logger:
  file_name: ./logs/log.json
  local_time: false
  max_size: 10
  max_backups: 10
  max_age: 30

pgsql:
  host: 127.0.0.1
  port: 5434
  user: root
  password: password
  name: product
  ssl_mode: disable