global:
  sendAnonymousUsage: false
entryPoints:
  web:
    address: :80
log:
  level: "DEBUG"
  filePath: "/etc/traefik/logs/debug.log"
api:
  dashboard: true
  insecure: true
metrics:
  prometheus:
    addEntryPointsLabels: true
    buckets: [0.1, 0.3, 1.2, 5.0]
providers:
  docker:
    watch: true
    exposedByDefault: false
    network: shop-infrastructure_default
  file:
    directory: /etc/traefik/dynamic
    filename: dynamic.yml
    watch: true
accessLog:
  filePath: "/etc/traefik/logs/access.log"