-- +migrate Up
CREATE TABLE IF NOT EXISTS products (
  ID SERIAL PRIMARY KEY,

  name VARCHAR NOT NULL,
  quantity INTEGER NOT NULL,

  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at timestamp NULL
);

-- +migrate Down
DROP TABLE IF EXISTS products;
