http:
  # Routers
  routers:
    shop_customer:
      entrypoints: web
      rule: "Host(`shop.local`) && PathPrefix(`/c`)"
      service: shop_customer
      middlewares:
        - strip_customer_path
    shop_order:
      entrypoints: web
      rule: "Host(`shop.local`) && PathPrefix(`/o`)"
      service: shop_order
      middlewares:
        - strip_order_path
    shop_product:
      entrypoints: web
      rule: "Host(`shop.local`) && PathPrefix(`/p`)"
      service: shop_product
      middlewares:
        - strip_product_path

  # Services
  services:
    shop_customer:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8000"
    shop_order:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8001"
    shop_product:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8002"

  middlewares:
    strip_customer_path:
      stripprefix:
        prefixes: "/c"
    strip_product_path:
      stripprefix:
        prefixes: "/p"
    strip_order_path:
      stripprefix:
        prefixes: "/o"

#  services:
#    shop_order:
#      loadbalancer:
#        servers:
#          port:8000
#http:
#  # Routers
#  routers:
#    shop_order:
#      service: shop_order
#      entrypoints: web
#      rule: "Host(`shop.local`) && Path(`oder`)"
#
#
#  # Services
#  services:
#    shop_order:
#      loadbalancer:
#        server:
#          port:8000
